"""The reproducibility bench: aggregate every reproduction under a directory
into one board — what was reproduced, the verdict, and the boundary it ran on.

Scans for reproduction records: any directory containing a
`claim_result_matrix.json` (a published repo) or a bundle's `summary.json`.
Produces a portfolio-ready markdown table plus machine-readable JSON.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

VERDICT_ORDER = ["REPRODUCED", "PARTIAL", "NOT_REPRODUCED", "INCONCLUSIVE"]


def _read(path: Path) -> dict | None:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None


def collect(root: Path) -> list[dict]:
    """One entry per reproduction found under root (deduped by matrix path)."""
    entries: list[dict] = []
    seen: set[Path] = set()
    for matrix_path in sorted(root.rglob("claim_result_matrix.json")):
        if matrix_path in seen:
            continue
        seen.add(matrix_path)
        matrix = _read(matrix_path)
        if not matrix:
            continue
        # The run manifest, if it sits beside the matrix, carries the boundary.
        manifest = _read(matrix_path.with_name("experiment_manifest.json")) or {}
        claims = matrix.get("claims") or []
        entries.append({
            "paper_id": matrix.get("paper_id") or "unknown",
            "verdict": matrix.get("overall_verdict") or "INCONCLUSIVE",
            "claims": len(claims),
            "reproduced_claims": sum(1 for c in claims if c.get("verdict") == "REPRODUCED"),
            "boundary": manifest.get("boundary"),
            "image_digest": manifest.get("image_digest"),
            "evaluated_at": matrix.get("evaluated_at"),
            "location": str(matrix_path.parent),
        })
    return entries


def build_index(root: Path) -> dict:
    entries = collect(root)
    summary = {v: sum(1 for e in entries if e["verdict"] == v) for v in VERDICT_ORDER}
    summary["total"] = len(entries)
    entries.sort(key=lambda e: (VERDICT_ORDER.index(e["verdict"])
                                if e["verdict"] in VERDICT_ORDER else 99,
                                e.get("evaluated_at") or ""), reverse=False)
    return {"generated_at": _now(), "root": str(root), "summary": summary, "entries": entries}


def _now() -> str:
    # Stamped by the caller-visible clock; kept isolated for testability.
    return datetime.now(timezone.utc).isoformat()


def render_md(index: dict) -> str:
    s = index["summary"]
    lines = [
        "# Reproducibility bench", "",
        f"{s['total']} reproduction(s): "
        + ", ".join(f"**{s[v]} {v.lower().replace('_', ' ')}**" for v in VERDICT_ORDER if s[v]) or "none yet",
        "",
        "| Paper | Verdict | Claims | Boundary | When |",
        "|---|---|---|---|---|",
    ]
    for e in index["entries"]:
        when = (e.get("evaluated_at") or "")[:10]
        claims = f"{e['reproduced_claims']}/{e['claims']}"
        lines.append(f"| {str(e['paper_id'])[:60]} | {e['verdict']} | {claims} | "
                     f"{e.get('boundary') or '-'} | {when} |")
    lines += ["", "_Generated by `gym index`. Verdicts use tolerances registered before each run._", ""]
    return "\n".join(lines)
